// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqiVC9vxFBkVckTGZNHp8YhmdepNFeadQ',
    appId: '1:679449850142:android:20af93fa63e3a38d9e590f',
    messagingSenderId: '679449850142',
    projectId: 'igdb-api-66740',
    databaseURL: 'https://igdb-api-66740-default-rtdb.firebaseio.com',
    storageBucket: 'igdb-api-66740.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANly6w6hYFfEb1VBUSJEI7sAxP420MbfA',
    appId: '1:679449850142:ios:0a7d09643bc810019e590f',
    messagingSenderId: '679449850142',
    projectId: 'igdb-api-66740',
    databaseURL: 'https://igdb-api-66740-default-rtdb.firebaseio.com',
    storageBucket: 'igdb-api-66740.appspot.com',
    iosBundleId: 'com.mottu.marvel.mottuMobileMarvel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANly6w6hYFfEb1VBUSJEI7sAxP420MbfA',
    appId: '1:679449850142:ios:0a7d09643bc810019e590f',
    messagingSenderId: '679449850142',
    projectId: 'igdb-api-66740',
    databaseURL: 'https://igdb-api-66740-default-rtdb.firebaseio.com',
    storageBucket: 'igdb-api-66740.appspot.com',
    iosBundleId: 'com.mottu.marvel.mottuMobileMarvel',
  );

}